// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVlcOXQ_afT4RteTAZnuP4zc8e0GBUx48',
    appId: '1:636603044308:web:29d6d0fa5c1289ca690641',
    messagingSenderId: '636603044308',
    projectId: 'using-riverpod-todo-app',
    authDomain: 'using-riverpod-todo-app.firebaseapp.com',
    storageBucket: 'using-riverpod-todo-app.appspot.com',
    measurementId: 'G-S7VSLSBFHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu1iHyEgOEF8MmUi6iZo3_0LjHN52tmO4',
    appId: '1:636603044308:android:379fb96a9ded08f9690641',
    messagingSenderId: '636603044308',
    projectId: 'using-riverpod-todo-app',
    storageBucket: 'using-riverpod-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpX6lHT09dc9gXJ828aciXmADKdKCfPeU',
    appId: '1:636603044308:ios:87a07f72bfe767eb690641',
    messagingSenderId: '636603044308',
    projectId: 'using-riverpod-todo-app',
    storageBucket: 'using-riverpod-todo-app.appspot.com',
    iosClientId: '636603044308-ueeeapvqvnch0rborgco4rimmtpd95o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.usingRiverpodTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpX6lHT09dc9gXJ828aciXmADKdKCfPeU',
    appId: '1:636603044308:ios:87a07f72bfe767eb690641',
    messagingSenderId: '636603044308',
    projectId: 'using-riverpod-todo-app',
    storageBucket: 'using-riverpod-todo-app.appspot.com',
    iosClientId: '636603044308-ueeeapvqvnch0rborgco4rimmtpd95o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.usingRiverpodTodoApp',
  );
}
